builders:

  tailwindBuilder:
    import: "package:jaspr_wrapper/builder.dart"
    builder_factories: ["tailwindBuilder"]
    build_extensions: {"^lib/{{}}.dart": ["lib/tailwind/{{}}.tailwind.dart"]}
    build_to: source
    auto_apply: dependents
